faceyspacey/extract-css-chunks-webpack-plugin

.eslintrc
hotModuleReplacement.js
index.js

Cleanup whitespaces and make it pass with eslint

---

hotModuleReplacement.js

Update the logic for comparing link tags' URLs so that the correct pathname is matched against.
Fixes #23.

fix($hmr): Target correct link tags when hot reloading.

---

index.js
loader.js

This fixes issues when environment variable is not configured before importing the module... which can be true for I figure a lot of Webpack configuration generators/factories like [edge-builder](https://github.com/sebastian-software/edge-builder). It imports dependencies via ESM import and executes the `main` function afterwards to parse command line arguments, etc.

Moved querying of environment variable

---

index.js

This change will remove the annoying, and will be backwards compatible.
P.S I noticed the tests are failing so I couldn't rely on them.
> DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead

Align with webpack api.

---

README.md

HMR & its dependent environment variable

---

index.js

Fixes #41.
extract-text-webpack-plugin had this bug: http://bit.ly/2ueFvXt
and was fixed with: http://bit.ly/2hCkpOf
So I borrowed the odering code from there and applied it to this plugin to fix ordering.

Fix css module ordering

---

loader.js

My webpack setup uses both `extract-text-webpack-plugin` and this package, in different situations.  So I was scratching my head for a while when I got this error message that referenced extract-text but was really coming from this one.
Anyways, there are a few other places that have `extract-text-webpack-plugin` in the loader, but I left them alone because I don't know how they're used, and maybe they're necessary.  But I think it's safe to fix the error message.

Fix error message to refer to correct plugin

---

index.js

See https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/66

Fix for 'chunk is not an instance of Chunk'

---

.eslintrc.js
README.md
src/hotModuleReplacement.js

Arrow functions break IE11 (whats new), updated eslint so it wont auto fix it
fix #83

fix(.eslintrc,hotModuleReplacement.js): Update linting rules, no arrows

---

src/hotModuleReplacement.js

[Element.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) is not supported in IE11.

Fix el.remove()

---

.github/CODEOWNERS
package.json
src/index.js

When using oneOf, HRM is never activated. This patch improved the lookup system used for determining
if CSS can and should be reloaded. There have been some other tweaks for css modules and HMR
fix #98,#80

fix: Fixed HMR issue when oneOf is used

---

package.json
src/hotLoader.js
src/hotModuleReplacement.js
src/index.js
src/loader.js

- Merging a PR which improved upon my initial code which allowed the plugin to automatically hot
reload. With the help of React Static, we are able to fix a bug that appeared when building out
build toolchains. This bug causes the pugin to have two seperate context references within webpack
and ends up passing incorrect references to the wrong instance. Deceptivally simple solution was
naming the context key myself.
-fix(nested-loaders-hmr): Fix n-depth nested loader usage where HMR fail
Currently on npm under the `next` tag
regarding #105

fix(index.js): Improved HMR detection multi instance collisions 

---

README.md
src/index.js

Add an option to disable warnings relating to consistent CSS import order as seen in https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250, as there does not seem to be a clear way to find and fix the source of the warnings.

Add a orderWarnings flag to disable warnings about CSS import order

---

README.md
src/index.js
test/cases/function-loader/expected/main.css
test/cases/function-loader/index.js
test/cases/function-loader/style.css
test/cases/function-loader/webpack.config.js

updateWebpackConfig previously expected `use` entries to be strings or arrays, and would throw `needle.includes is not a function` errors when given a function that returns a loader object.
I ran into this while using react-svg-loader:
```js
{
test: /\.svg$/,
use: [
({resource}) => {
const prefix = `svg${stringHash(
path.relative(webDir, resource)
)}`
return {
loader: 'react-svg-loader',
options: {
svgo: {
plugins: [
{
cleanupIDs: {
prefix
}
}
]
}
}
}
}
]
}
```
It uses a function to return a loader object per resource, so that svgo can be instructed to give svgs unique ids.

fix(index.js): Support function loaders

---

.babelrc

Cause `hotModuleReplacement.js` will be used in browsers, it needs to be compiled for low version browsers

add browsers to babelrc's target

---

src/hotLoader.js

Remove the exclamation point so that HMR can be handled by other loader.
e.g: babel-loader.

fix:Improved path Settings for hotloader.js load hmr.js (#118)

---

README.md

Resolving old issue about incorrect  statement about next.js
Fix: #84

docs: remove incorrect statement about next.js

---

package.json

broke the release when copying changes back over from the pull request to mini-css

fix: fixing semantic-release after rewrite

---

package.json
src/loader.js
test/cases/hmr/expected/main.js

if local scoped hash maps were not returned, the loader was not adding HMR to the file at all.

fix: broken hot reloading of global styles

---

src/loader.js
test/cases/css-modules/expected/main.css
test/cases/css-modules/expected/main.js
test/cases/css-modules/index.css
test/cases/css-modules/webpack.config.js

Fixes #151. The css modules output was not added to `module.exports` if `hot` was `false`.
Added a test to go with it.

Fix missing css modules output

---

src/index.js

The flag defaults to true, which retains the existing behaviour of
warnings when there is conflicting import order between multiple CSS
files. When set to false, these warnings are not generated.
Note that there is no new documentation because the `orderWarnings` flag is already documented in the README

feat: add orderWarnings flag

---

src/hmr/hotModuleReplacement.js

This change is to keep the link tags on the same place in the dom as there where from the beginning. This is to keep the order of css assets. 
e.g. if you have a inline style tag last in your document that overwrite css from linked stylesheets, after HMR have compiled and inserted new links to the stylesheets, the the inline styles are still last and the import order for the css rules are still correct

Switch appendChild to replaceBefore in hmr script

---

src/hmr/hotModuleReplacement.js

Condition not required as URLs are absolute in most cases.
```
<script defer async src="/0.js"></script>
// element.src -> https://domain.com/0.js
normalizeURL("domain.com/0.js")
// https://domain.com/0.js
```

Remove absolute URL condition from HMR request checker.

---

package.json
yarn.lock

Fixes #174
Similar to the fix for mini-css-extract-plugin:
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/385
- https://github.com/webpack-contrib/mini-css-extract-plugin/pull/399

fix: downgrade normalize-url to version 1.9.1

---

src/index.js

fixes faceyspacey/extract-css-chunks-webpack-plugin#264

fix: restore `insert` option functionality

---

index.d.ts
package.json

Fixes #89… again. I had to guess what some options did, so you may want to look into the comments (in `index.d.ts`) and check if they all make sense. Besides that, it should work.

fix: add TS declarations

---

index.d.ts

Because else it doesn't work with:
```
{
loader: CssExtractPlugin.loader,
options: { hmr: !production && target !== 'node' },
}
```
type Loader is `string | NewLoader` and `NewLoader` is:
```
interface NewLoader {
loader: string;
options?: { [name: string]: any };
}
```

fix: ExtractCssChunksPlugin.loader is a string

---

src/index.js
test/HMR.test.js
test/TestCases.test.js
test/__snapshots__/HMR.test.js.snap
test/cases/insert-function/expected/main.js
test/cases/insert-function/webpack.config.e2e.js
test/cases/insert-string/expected/main.js
test/cases/insert-string/webpack.config.e2e.js
test/cases/publicpath-emptystring/expected/main.css
test/cases/publicpath-function/expected/nested/again/style.css
test/cases/publicpath-function/expected/nested/style.css
test/cases/publicpath-trailing-slash/expected/main.css
test/cases/simple-publicpath/expected/main.css
test/cases/split-chunks/index.js
test/inject-option.test.js

**Description:**
* Checks if browser supports `<link rel="preload">`. If not, fallback to original functionality
* Adds extracted stylesheet preload
* Listens to `onload` event of preload, adds stylesheet when fired.
Forked implementation of https://github.com/webpack-contrib/mini-css-extract-plugin/pull/344
Originated in https://github.com/nuxt/nuxt.js/issues/8060
Fixes #260 
* No breaking changes
* Updated tests, all pass ✅
* Does this also need updates to the documentation?

feat: preload css

---

src/index.js

I'm using nuxt.js which use extract-css-chunks-webpack-plugin under the hood, I ran into an error where it says:
`ERROR in chunk 159
159.9676669.css
Cannot read property 'pop' of undefined`
I just added validation before pop().

fix: Check if bestMatch exists before pop()
